version: "2"
services:
  api:
    container_name: language-api
    build: .
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/project/src
    command: ["npm", "run", "dev"]